---
- name: Add Jupyter repo
  kubernetes.core.helm_repository:
    binary_path: "{{ helm_bin_path }}"
    name: jupyterhub
    repo_url: "https://hub.jupyter.org/helm-chart/"

- name: DEBUG - values.yaml
  debug:
    msg: "{{ lookup('template', 'values.yaml') | from_yaml }}"
  when: debug | default(false)
  
- name: Deploy Jupyter with helm
  kubernetes.core.helm:
    binary_path: "{{ helm_bin_path }}"
    name: jupyter
    chart_ref: jupyterhub/jupyterhub
    #chart_version: 0.5.12
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
    release_namespace: "{{ kube_namespace }}"
    update_repo_cache: true