---
- name: Add open-webui repo
  kubernetes.core.helm_repository:
    binary_path: "{{ helm_bin_path }}"
    name: open-webui
    repo_url: "https://open-webui.github.io/helm-charts"

- name: DEBUG - values.yaml
  debug:
    msg: "{{ lookup('template', 'values.yaml') | from_yaml }}"
  when: debug | default(false)
  
- name: Deploy Open WebUI with helm
  kubernetes.core.helm:
    binary_path: "{{ helm_bin_path }}"
    name: open-webui
    chart_ref: open-webui/open-webui
    #chart_version: 0.5.18
    values: "{{ lookup('template', 'values.yaml') | from_yaml }}"
    release_namespace: "{{ kube_namespace }}"
    update_repo_cache: true